name = "Git Config"
grammar = "git_config"
path_suffixes = [
  # https://github.com/neovim/neovim/blob/master/runtime/lua/vim/filetype.lua
  "config.worktree",
  ".gitconfig",
  ".gitmodules",
  ".lfsconfig",
]
line_comments = ["; "]
autoclose_before = "]"
brackets = [
  { start = "[", end = "]", close = true, newline = false },
]
